# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  CI: true

jobs:
  build:
    name: Node.js, version from .nvmrc on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Prepare git
        run: git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v4

        # Instal yarn berry
      - name: Enable corepack
        run: corepack enable yarn

      - name: Setup yarn
        run: yarn set version berry

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install yarn dependencies
        run: yarn --immutable

      - name: Compile TypeScript files
        run: yarn build

      - name: Run lint rules
        run: yarn lint --report-unused-disable-directives

      # TODO: Fix tests
      # - name: Run tests
      #   run: yarn testonly:cov -- --colors

      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v1
      #   with:
      #     fail_ci_if_error: true
